info:
  component: Edge Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:6000000

zuul:
  prefix: /api
  routes:
    create-patient:
      path: /patient
      serviceId: cliniko-web
    dash-board:
      path: /dashboard
      serviceId: cliniko-web
    admin:
      path: /admin
      serviceId: cliniko-web
    result:
          path: /result
          serviceId: cliniko-web

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false

server:
  port: 9090

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG